#!/usr/bin/env bash
# AI-free templated factory: turn a GitHub issue into a deterministic
# spec + plan + code stub, on a branch, with a PR. No LLM, no API keys, no cost.
#
# Usage:  bash scripts/factory.sh <issue-number>
# Env:    REPO=owner/name        (defaults to the repo this script lives in)
#         STUB_LANG=py|js|ts|go  (code-stub language; default py)
#
# Requires: git, gh (authenticated). Both are preinstalled on GitHub runners.
set -euo pipefail

# Always operate from the repo root, regardless of where we're invoked from.
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

N="${1:?usage: factory.sh <issue-number>}"
REPO="${REPO:-$(gh repo view --json nameWithOwner --jq .nameWithOwner)}"

# --- read the issue (deterministic inputs) ---
title=$(gh issue view "$N" -R "$REPO" --json title  --jq .title)
labels=$(gh issue view "$N" -R "$REPO" --json labels --jq '[.labels[].name] | join(", ")')

slug=$(printf '%s' "$title" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')
[ -n "$slug" ] || slug="issue-$N"
func=$(printf '%s' "$slug" | tr '-' '_')

# code-stub language (default py); validated against the supported set
STUB_LANG="${STUB_LANG:-py}"
case "$STUB_LANG" in
  py|js|ts|go) ;;
  *) echo "ERROR: unsupported STUB_LANG '$STUB_LANG' (use: py, js, ts, go)" >&2; exit 2 ;;
esac

dir="factory/issue-${N}-${slug}"
branch="factory/issue-${N}-${slug}"
today=$(date -u +%Y-%m-%d)

# git identity (runners start with none)
git config user.name  >/dev/null 2>&1 || git config user.name  "agent-factory"
git config user.email >/dev/null 2>&1 || git config user.email "factory@users.noreply.github.com"

git fetch origin main --quiet || true
git checkout -B "$branch" origin/main 2>/dev/null || git checkout -B "$branch"
mkdir -p "$dir"

# --- SPEC.md ---
{
  echo "# Spec — Issue #${N}: ${title}"
  echo
  echo "> Generated by the AI-free templated factory on ${today}. Deterministic — no LLM, no API keys, no cost."
  echo
  echo "## Source issue"
  echo "- Number: #${N}"
  echo "- Title: ${title}"
  echo "- Labels: ${labels:-none}"
  echo "- Link: https://github.com/${REPO}/issues/${N}"
  echo
  echo "## Summary (from the issue body)"
  echo
} > "$dir/SPEC.md"
gh issue view "$N" -R "$REPO" --json body --jq .body >> "$dir/SPEC.md"
cat >> "$dir/SPEC.md" <<'EOF'

## Acceptance criteria
- [ ] Behavior matches the summary above
- [ ] Tests added or updated
- [ ] Docs updated if needed

## Out of scope
- _fill in_
EOF

# --- PLAN.md ---
cat > "$dir/PLAN.md" <<EOF
# Plan — Issue #${N}: ${title}

- [ ] Implement \`${func}()\` in ${slug}.${STUB_LANG} per SPEC.md
- [ ] Add tests
- [ ] Update docs
- [ ] Request review and link #${N}
EOF

# --- code stub (language selected by STUB_LANG) ---
stub="$dir/${slug}.${STUB_LANG}"
case "$STUB_LANG" in
  py)
    cat > "$stub" <<EOF
"""${title}

Spec:  ./SPEC.md
Issue: #${N}  (https://github.com/${REPO}/issues/${N})

Auto-generated stub from the AI-free templated factory. Implement the TODO.
"""


def ${func}():
    """TODO: implement per SPEC.md (issue #${N})."""
    raise NotImplementedError("scaffold only — see SPEC.md")


if __name__ == "__main__":
    ${func}()
EOF
    ;;
  js)
    cat > "$stub" <<EOF
// ${title}
// Spec:  ./SPEC.md
// Issue: #${N}  (https://github.com/${REPO}/issues/${N})
// Auto-generated stub from the AI-free templated factory. Implement the TODO.

export function ${func}() {
  // TODO: implement per SPEC.md (issue #${N})
  throw new Error("scaffold only — see SPEC.md");
}
EOF
    ;;
  ts)
    cat > "$stub" <<EOF
// ${title}
// Spec:  ./SPEC.md
// Issue: #${N}  (https://github.com/${REPO}/issues/${N})
// Auto-generated stub from the AI-free templated factory. Implement the TODO.

export function ${func}(): void {
  // TODO: implement per SPEC.md (issue #${N})
  throw new Error("scaffold only — see SPEC.md");
}
EOF
    ;;
  go)
    gofunc=$(printf '%s' "$func" | sed -E 's/(^|_)([a-z])/\U\2/g')
    cat > "$stub" <<EOF
// ${title}
// Spec:  ./SPEC.md
// Issue: #${N}  (https://github.com/${REPO}/issues/${N})
// Auto-generated stub from the AI-free templated factory. Implement the TODO.

package factory

// ${gofunc} TODO: implement per SPEC.md (issue #${N}).
func ${gofunc}() {
	panic("scaffold only — see SPEC.md")
}
EOF
    ;;
esac

# --- commit, push, PR ---
git add "$dir"
git commit -m "factory: scaffold issue #${N} (${slug})" --quiet
git push -u origin "$branch" --quiet

pr_url=$(gh pr create -R "$REPO" --base main --head "$branch" \
  --title "Factory: #${N} ${title}" \
  --body "Deterministic scaffold for #${N} — generated by \`scripts/factory.sh\` (no AI). Files in \`${dir}/\`: SPEC.md, PLAN.md, ${slug}.${STUB_LANG}. Refs #${N}." \
  2>/dev/null) || pr_url="(PR already exists for $branch)"

echo "Generated: $dir/{SPEC.md,PLAN.md,${slug}.${STUB_LANG}}"
echo "Branch:    $branch"
echo "PR:        $pr_url"
